package com.reticket.reticket.security;

public enum AuthorityEnum {

    SELL_TICKET,
    RESERVE_TICKET,
    RETURN_TICKET,
    BUY_TICKET,
    LIST_TICKETS,
    LIKE_LIST_PLAY,
    ACCESS_REPORT,
    CREATE_AND_UPDATE_THEATER,
    CREATE_AND_UPDATE_CONTRIBUTOR_PRICE_PLAY_PERFORMANCE,
    CREATE_AND_UPDATE_ADDRESS_AUDITORIUM,
    CREATE_AND_UPDATE_ASSOCIATE

}
